[package]
name = "address"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "1.5.3"
solana-program = "2.1.6"

[dev-dependencies]
solana-program-test = "2.1.6"
solana-sdk = "2.1.6"
tokio = "1.42.0"
address = { path = "." }
